In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('raw.csv')

In [4]:
df.head(5)

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group C,associate's degree,standard,none,91,86,84
1,female,group B,some college,free/reduced,completed,53,66,73
2,male,group D,bachelor's degree,standard,none,80,73,72
3,male,group C,some college,free/reduced,none,74,77,73
4,male,group E,some college,standard,completed,84,83,78

In [ ]:
#Check The Missing Values

df.isna().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [8]:
#Duplicate Values

df.duplicated().sum()

np.int64(0)

In [9]:
#Check DataTypes

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       200 non-null    object
 1   race_ethnicity               200 non-null    object
 2   parental_level_of_education  200 non-null    object
 3   lunch                        200 non-null    object
 4   test_preparation_course      200 non-null    object
 5   math_score                   200 non-null    int64
 6   reading_score                200 non-null    int64
 7   writing_score                200 non-null    int64
dtypes: int64(3), object(5)
memory usage: 12.6+ KB

In [10]:
#Check Number of Unique Values

df.nunique()

gender                          2
race_ethnicity                  5
parental_level_of_education     6
lunch                           2
test_preparation_course         2
math_score                     60
reading_score                  60
writing_score                  63
dtype: int64

In [11]:
#Check Statistics of Dataset

df.describe()

       math_score  reading_score  writing_score
count  200.000000       200.0000     200.000000
mean    64.460000        67.6250      66.445000
std     15.638453        15.0805      15.563679
min      0.000000        17.0000      10.000000
25%     55.000000        57.0000      56.000000
50%     66.000000        70.0000      69.000000
75%     76.000000        78.0000      77.000000
max    100.000000        99.0000     100.000000

In [13]:
print(df['test_preparation_course'].unique())
print(df['parental_level_of_education'].unique())

['none' 'completed']
["associate's degree" 'some college' "bachelor's degree"
 'some high school' 'high school' "master's degree"]

In [14]:
#Define Commercial or CAtegoral Columns

numeric_features = [feature for feature in df.columns if df[feature].dtype != 'O']
categoral_features = [feature for feature in df.columns if df[feature].dtype == 'O']

print("We have {} numerical features: {}".format(len(numeric_features),numeric_features))
print("We have {} categoral feature: {}".format(len(categoral_features),categoral_features))

We have 3 numerical features: ['math_score', 'reading_score', 'writing_score']
We have 5 categoral feature: ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']

In [21]:
#Adding Columns for "Total Score" and "Average"

df['total_score'] = df['math_score'] + df['reading_score'] + df['writing_score']
df['average'] = df['total_score']/3
df = df.drop('average_score', axis=1)
df.head(5)

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total_score,average
0,female,group C,associate's degree,standard,none,91,86,84,261,87.000000
1,female,group B,some college,free/reduced,completed,53,66,73,192,64.000000
2,male,group D,bachelor's degree,standard,none,80,73,72,225,75.000000
3,male,group C,some college,free/reduced,none,74,77,73,224,74.666667
4,male,group E,some college,standard,completed,84,83,78,245,81.666667

In [22]:
reading_full = df[df['reading_score'] == 100]['average'].count()
writing_full = df[df['writing_score'] == 100]['average'].count()
math_full = df[df['math_score'] == 100]['average'].count()

print(f"number of Students with full marks in Maths: {math_full}")
print(f"Number of Students with full marks in Writing: {writing_full}")
print(f"Number of Students with full marks in Reading: {reading_full}")

number of Students with full marks in Maths: 1
Number of Students with full marks in Writing: 1
Number of Students with full marks in Reading: 0

In [24]:
reading_less_20 = df[df['reading_score'] <= 20]['average'].count()
writing_less_20 = df[df['writing_score'] <= 20]['average'].count()
math_less_20 = df[df['math_score'] <= 20]['average'].count()

print(f"Number of Students with less than 20 in reading: {reading_less_20}")
print(f"number of Students with less than 20 in writing: {writing_less_20}")
print(f"Number of Students with less than 20 in Maths: {math_less_20}")

Number of Students with less than 20 in reading: 1
number of Students with less than 20 in writing: 2
Number of Students with less than 20 in Maths: 2